export const AppConfigs = {
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  USER_SERVICE_URI: process.env.USER_SERVICE_URI,
  ONELOGIN_CLIENT_ID: process.env.ONELOGIN_CLIENT_ID,
  ONELOGIN_CLIENT_SECRET: process.env.ONELOGIN_CLIENT_SECRET,
  ONELOGIN_ISSUER: process.env.ONELOGIN_ISSUER,
};
